export const SELECT_CURRENCY = "SELECT_CURRENCY";
export const UPDATE_CURRENCY_AMOUNT = "UPDATE_CURRENCY_AMOUNT";
export const SWITCH_SOURCE_TARGET_CURRENCY = "SWITCH_SOURCE_TARGET_CURRENCY";
export const SELECT_MENU_CURRENCY = "SELECT_MENU_CURRENCY";
